// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/users/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/users/[id].put').default>>>>
    }
    '/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/users/index.post').default>>>>
    }
  }
}
export {}